/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2020 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include <stdio.h>
#include <stdint.h>

#define ADC_BASE_ADDR		( 0x40012000UL)
#define ADC_CR1_OFFSET		( 0x04UL )
#define ADC_CR1_REG_ADDR 	( ADC_BASE_ADDR + ADC_CR1_OFFSET )

#define RCC_BASE_ADDR		( 0x40023800UL )
#define RCC_APB2ENR			( 0x44UL )
#define RCC_APB2ENR_ADDR	( RCC_BASE_ADDR + RCC_APB2ENR )

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
	uintptr_t volatile *const pAPB2EnReg = (uintptr_t*) RCC_APB2ENR_ADDR;
	uintptr_t volatile *const pAdcCr1Reg =  (uintptr_t*) ADC_CR1_REG_ADDR;

	// Enable APB2 Clock: ADC1 is on APB2
	*pAPB2EnReg |= ( 1 << 8 );

	// Set ADC Control Regeister - Scan (just an example - not doing anything)
	*pAdcCr1Reg |= ( 1 << 8 );

    /* Loop forever */
	for(;;);
}
